display:
  screen_resolution: [1360, 768]
  tick_size: 0.02
  meters_per_pixel: 0.15
  scale_factor: 0.75
starfield:
  num_stars: [700, 500, 200]
  parallax_rate: [1.2, 0.8, 0.4]
  luminosity: [200, 150, 100]
